Add_notificacao_crud
team-conectar/conectar-backend pull request #16
Opened 2021-04-05 17:47 UTC by CristianVeggian

2021-04-05 18:19 UTC, lincolncosta requested changes

2021-04-05 18:19 UTC, lincolncosta commented on app/api/api_v1/routers/notificacao.py
> +    #current_pessoa=Depends(get_current_active_pessoa),
Acredito que isso não deveria estar comentado (também checar nos demais endpoints)

2021-04-05 18:19 UTC, lincolncosta commented on app/db/notificacao/schemas.py
> +class NotificacaoBase(BaseModel):
Foram criadas as colunas de data? Com a data de criação da notificação e a data de leitura da mesma

2021-04-05 18:19 UTC, lincolncosta commented on app/db/notificacao/crud.py
> +def check_notificacao_vaga(db: Session):
Foi criada alguma validação pra evitar notificações duplicadas? Como naquele caso do cron recriar a mesma notificação várias vezes

2021-04-05 18:19 UTC, lincolncosta commented on app/db/notificacao/crud.py
> +            and hoje.day != models.PessoaProjeto.data_atualizacao.day)\
Acho que != é muito amplo, seria legal considerar somente as pendências que estejam dentro do limite de dias que criamos. Além disso, acho que essa consulta pode gerar bugs porque somente o dia é considerado, enquanto o mês e o ano são ignorados.

2021-04-09 19:59 UTC, closed without merging

2021-04-09 19:59 UTC, CristianVeggian commented
Correções feitas - Novo PR aberto